### ISSUE TITLE
heterotachy.py error

### ISSUE THREAD

**Issue by thesamuanels** [TheBrownLab/PhyloFisher#124]
Hello, I have been trying to use the heterotachy.py script (phylofisher v1.2.14):

`heterotachy.py -tr matrix_FULL.fa.treefile -m matrix_FULL.fa -s 2216`

*.treefile is the output tree from iqtree2
matrix_FULL.fa is the original matrix constructed at the end of the phylofisher workflow

However, here is what happens when I try to run it:

`Traceback (most recent call last):
  File "/opt/Anaconda3/envs/fisher_1.2.14/lib/python3.7/site-packages/ete3/coretype/tree.py", line 235, in __and__
    first_match = next(self.iter_search_nodes(name=value))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Anaconda3/envs/fisher_1.2.14/bin/heterotachy.py", line 289, in <module>
    series, size = get_branch_lens()
  File "/opt/Anaconda3/envs/fisher_1.2.14/bin/heterotachy.py", line 93, in get_branch_lens
    node2 = tree & taxon2
  File "/opt/Anaconda3/envs/fisher_1.2.14/lib/python3.7/site-packages/ete3/coretype/tree.py", line 238, in __and__
    raise TreeError("Node not found")
ete3.coretype.tree.TreeError: 'Node not found'`

I have used the same data for the fast_site_removal.py script, and that one worked perfectly.
Any idea why this happens? Thanks

**Comment by robert-ervin-jones** [comment]
Hi @thesamuanels,

I suspect there may be an issue with your tree file. Do you mind sharing your tree file and matrix so I can try to reproduce the error? 

Best,
Robert
