### ISSUE TITLE
Error with test data, informant.py ValueError: cannot set a frame with no defined columns

### ISSUE THREAD

**Issue by pyongheng** [TheBrownLab/PhyloFisher#28]
I was trying to test the installation of phylofisher and keep getting an error at informant.py step from testinstall.sh.
Fisher completes without errors but at the next step it gives the error below. 

```
Traceback (most recent call last):
  File "/Users/yonghengphua/opt/anaconda3/envs/fisher/bin/informant.py", line 278, in <module>
    res = table_with_routes(matrix, routes)
  File "/Users/yonghengphua/opt/anaconda3/envs/fisher/bin/informant.py", line 101, in table_with_routes
    df.loc[taxon] = len(df.columns) * [0]
  File "/Users/yonghengphua/opt/anaconda3/envs/fisher/lib/python3.7/site-packages/pandas/core/indexing.py", line 692, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/Users/yonghengphua/opt/anaconda3/envs/fisher/lib/python3.7/site-packages/pandas/core/indexing.py", line 1629, in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
  File "/Users/yonghengphua/opt/anaconda3/envs/fisher/lib/python3.7/site-packages/pandas/core/indexing.py", line 1903, in _setitem_with_indexer_missing
    raise ValueError("cannot set a frame with no defined columns")
ValueError: cannot set a frame with no defined columns
```

**Comment by robert-ervin-jones** [comment]
Hi @pyongheng,

Thank you for bringing this to our attention. 

Can you confirm you are using v1.1.2 of PhyloFisher?

Best,
Robert

**Comment by robert-ervin-jones** [comment]
Hi @pyongheng,

After looking into this and discussing the matter with @atice, we have concluded that `testinstall.sh` is antiquated. If your conda install was successful, which it seems to have been, you are fine to proceed.

I am going to go ahead and close the issue. Please let us know if any other issues arise.

Best,
Robert
