### ISSUE TITLE
matrix_constructor.smk not found

### ISSUE THREAD

**Issue by cha-namoth** [TheBrownLab/PhyloFisher#72]
Hi guys,

ran into an issue with matrix_constructor.py in the latest phylofisher versions (1.2.3 and upwards I think). If I try to run:

`matrix_constructor.py -t 20 -i prep_final_dataset_out_Mar.14.2023`

It crashes immediately with this: 

```
Error: Snakefile "/opt/Anaconda3/envs/fisher/bin/matrix_constructor.smk" not found.
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/fisher/bin/matrix_constructor.py", line 131, in <module>
    run_snakemake()
  File "/opt/Anaconda3/envs/fisher/bin/matrix_constructor.py", line 86, in run_snakemake
    subprocess.run(smk_cmd, shell=True, executable='/bin/bash', check=True)
  File "/opt/Anaconda3/envs/fisher/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
```

This doesn't happen with phylofisher version 1.2.1, I assume because matrix_constructor wasn't ported over to snakemake yet.

Cheers,
Gordon

**Comment by cha-namoth** [comment]
Hi guys,
sorry to revive this – just finally managed to test the 1.2.7 version that was supposed to fix the matrix_constructor.smk issue. I'm now getting the following message:

```
ModuleNotFoundError in line 4 of /opt/Anaconda3/envs/fisher_1.2.7/bin/matrix_constructor.smk:
No module named 'Bio'
  File "/opt/Anaconda3/envs/fisher_1.2.7/bin/matrix_constructor.smk", line 4, in <module>
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/fisher_1.2.7/bin/matrix_constructor.py", line 139, in <module>
    run_snakemake()
  File "/opt/Anaconda3/envs/fisher_1.2.7/bin/matrix_constructor.py", line 88, in run_snakemake
    subprocess.run(smk_cmd, shell=True, executable='/bin/bash', check=True)
  File "/opt/Anaconda3/envs/fisher_1.2.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
```

Cheers,
Gordon

**Comment by robert-ervin-jones** [comment]
Hi Gordon,

Can you `conda install biopython` and try again?

Best,
Robert

**Comment by cha-namoth** [comment]
Still getting the same error unfortunately.
